config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, skip: [:sessions]

  as :user do
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post 'signin', to: 'devise/sessions#create', as: :user_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  resource :main, only: :index

  # Defines the root path route ("/")

  root 'main#index'

  resources :chats
  resources :chats_messages
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  has_many :messages, -> { order(created_at: :asc) }, class_name: 'ChatMessage', dependent: :destroy

  normalize_attributes :name, with: %i[blank squish]
  normalize_attributes :raw_schema, with: %i[blank strip]

  after_create_commit -> { send_user_notification('Your new chat has been created!') }
  after_destroy_commit -> { send_user_notification('Chat was successfully destroyed.') }

  validates :name, :raw_schema, :user_id, presence: true
  validate :schema_with_valid_sql

  def schema_with_valid_sql
    validator = SqlValidationService.new(raw_schema).verify!

    if validator.valid?
      if validator.parsed_result.tables.empty? || raw_schema.exclude?('CREATE TABLE')
        errors.add(
          :base,
          'No tables detected, please define tables in your schema to be able to work with Slonito'
        )
      else
        self.tables = validator.parsed_result.tables

        true
      end
    else
      errors.add(:base, "Invalid SQL: #{validator.error}")
    end
  end

  private

  def send_user_notification(message)
    broadcast_append_to "notifications_channel_from_user_#{user_id}",
                        renderable: SuccessToastComponent.new(message:),
                        target: 'notifications_container'
  end
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  # normalize_attributes :content, with: %i[blank strip]

  belongs_to :chat, inverse_of: :messages

  validates :content, :chat_id, presence: true

  delegate :raw_schema, to: :chat, prefix: true

  after_create_commit :send_user_message

  def content_to_markdown
    "\n#{content}\n"
  end

  def send_user_message
    if is_input?
      broadcast_remove_to "messages_from_chat_#{chat_id}", target: 'waiting_slonito_answer'
  
      broadcast_append_to "messages_from_chat_#{chat_id}",
                          renderable: UserMessageComponent.new(chat_message: self),
                          target: 'chat_container'
                      
      broadcast_append_to "messages_from_chat_#{chat_id}",
                          renderable: WaitingAnswerComponent.new,
                          target: 'chat_container'
    else
      broadcast_replace_to "messages_from_chat_#{chat_id}",
                           target: 'waiting_slonito_answer',
                           renderable: SlonitoMessageComponent.new(chat_message: self)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chats
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :turbo_frame_request_variant

  private

  def turbo_frame_request_variant
    request.variant = :turbo_frame if turbo_frame_request?
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  layout false

  before_action :authenticate_user!

  def index
    @chats = Chat.where(user_id: current_user.id).order(created_at: :desc)

    return if params[:query].blank?

    @chats = @chats.where('name ILIKE ?', "%#{params[:query]}%")
  end

  def show
    @chat = Chat.where(id: params[:id], user_id: current_user.id).includes(:messages).first!

    respond_to do |format|
      format.turbo_stream
      format.html { render :show, layout: 'main' }
    end
  end

  def new
    @chat = Chat.new
  end

  def create
    @chat = Chat.new(chat_params)
    @chat.user_id = current_user.id

    if @chat.save
      respond_to(&:turbo_stream)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @chat = Chat.where(id: params[:id], user_id: current_user.id).first!
    @chat.destroy

    respond_to(&:turbo_stream)
  end

  private

  def chat_params
    params.require(:chat).permit(:name, :raw_schema)
  end
end

app/controllers/chats_messages_controller.rb
class ChatsMessagesController < ApplicationController
  layout false

  before_action :authenticate_user!

  def create
    @message = ChatMessage.new(chat_message_params)
    @message.is_input = true

    if @message.save
      generate_response

      head :ok
    else
      head :unprocessable_entity
    end
  end

  private

  def chat_message_params
    params.require(:chat_message).permit(:content, :chat_id)
  end

  def generate_response
    response = ChatMessage.new(is_input: false, chat_id: @message.chat_id)

    response.content = SlonitoApiService.new(@message).get_response!
    response.save
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  layout 'main'

  before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/chats/create.turbo_stream.erb
<%= turbo_stream.before 'chat_window' do %>
  <script>
    history.pushState(null, "", "<%= chat_path(@chat) %>");
    document.getElementById("chats").reload()
  </script>
<% end %>

<%= turbo_stream.replace 'chat_window', ::ChatComponent.new(chat: @chat) %>

app/views/chats/destroy.turbo_stream.erb
<%= turbo_stream.before "chats" do %>
  <script>
    history.pushState(null, "", "/");
    document.getElementById("chats").reload();
  </script>
<% end %>

<%= turbo_stream.update "chat_window", partial: 'main/chat_container' %>

app/views/chats/index.html+turbo_frame.erb
<%= turbo_frame_tag 'chats' do %>
  <%- if @chats.present? %>
    <%= render ::ChatButtonComponent.with_collection(@chats) %>
  <%- else %>
    <small class="block text-center">Nothing to see here :(</small>
  <%- end %>
<% end %>

app/views/chats/new.html.erb
<%= turbo_frame_tag "new_chat_modal_frame" do %>
  <%= form_with(model: @chat, html: { class: "" }) do |form| %>
    <div class="mt-0 px-4 md:p-5">
      <div class="w-full space-y-4">
        <% if @chat.errors.any? %>
          <div class="flex p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-red-900 dark:text-red-300" role="alert">
            <svg class="flex-shrink-0 inline w-4 h-4 me-3 mt-[2px]" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
              <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
            </svg>
            <span class="sr-only">Danger</span>
            <div>
              <span class="font-medium">Ensure that these requirements are met:</span>
              <ul class="mt-1.5 list-disc list-inside">
                <%- @chat.errors.full_messages.each do |error| %>
                  <li><%= error %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :name, class: "block mb-2 text-sm font-medium text-stone-900 dark:text-white" %>
          <%= form.text_field :name, required: true, data: { action: "" }, class: "block p-2.5 w-full text-sm text-stone-900 bg-stone-50 rounded-lg border border-stone-300 focus:ring-green-500 focus:border-green-500 dark:bg-stone-600 dark:border-stone-500 dark:placeholder-stone-400 dark:text-white dark:focus:ring-green-500 dark:focus:border-green-500", placeholder: "My awesome chat 1" %>
        </div>

        <div class="field">
          <%= form.label :raw_schema, 'Schema', class: "block mb-2 text-sm font-medium text-stone-900 dark:text-white" %>
          <%= form.text_area :raw_schema, required: true, data: { action: "" }, class: "block p-2.5 w-full text-sm text-stone-900 bg-stone-50 rounded-lg border border-stone-300 focus:ring-green-500 focus:border-green-500 dark:bg-stone-600 dark:border-stone-500 dark:placeholder-stone-400 dark:text-white dark:focus:ring-green-500 dark:focus:border-green-500", placeholder: "CREATE TABLE...", rows: 12 %>
        </div>
      </div>
    </div>

    <div class="flex justify-end items-center p-4 md:p-5 border-t border-stone-200 rounded-b dark:border-stone-600">
      <%= form.submit 'Save', class: "cursor-pointer text-sm rounded-lg focus:z-10 focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800" %>
      <button data-action="click->modal#cancel" data-modal-hide="new_chat_modal" type="button" class="py-2.5 px-5 ms-3 text-sm font-medium text-stone-900 focus:outline-none bg-white rounded-lg border border-stone-200 hover:bg-stone-100 hover:text-green-700 focus:z-10 focus:ring-4 focus:ring-stone-100 dark:focus:ring-stone-700 dark:bg-stone-800 dark:text-stone-400 dark:border-stone-600 dark:hover:text-white dark:hover:bg-stone-700">Close</button>
    </div>
  <% end %>
<% end %>

app/views/chats/show.html+turbo_frame.erb
<%= render(::ChatComponent.new(chat: @chat)) %>

app/views/chats/show.html.erb
<%= render(::ChatComponent.new(chat: @chat)) %>

app/views/chats_messages/create.turbo_stream.erb
<%= turbo_stream.append "chat_messages", ::MessageComponent.new(chat_message: @message, go_down: true) %>

app/views/layouts/application.html.slim
doctype html
html class='h-full dark' lang="en"
  head
    title Slonito
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="turbo-cache-control" content="no-cache"
    meta name="turbo-refresh-method" content="morph"
    meta name="turbo-visit-control" content="reload"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"

  body class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8 dark:bg-stone-900 text-white"
    = yield

app/views/layouts/main.html.slim
doctype html
html class="dark" lang="en"
  head
    title Slonito
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"

  body class="bg-stone-50 dark:bg-stone-700"
    = turbo_include_tags

    = turbo_stream_from "notifications_channel_from_user_#{current_user.id}"
    div id='notifications_container'

    = render(::SidebarComponent.new)

    main class="md:ml-64 flex flex-col h-screen"
      = yield

    = render(::NewChatModalComponent.new)
    = render(::HelpModalComponent.new)

app/views/main/_chat_container.html.erb
<div id="chat_container" class="scroll-smooth snap-end w-full h-screen px-4 lg:px-12 sm:px-6 pb-10 flex-grow overflow-y-auto flex flex-col flex-1">
  <%= render(::NavbarComponent.new) %>
  <%= render(::HeroComponent.new) %>
</div>

app/views/main/index.html.erb
<%= turbo_frame_tag 'chat_window', class: "flex flex-col flex-1 h-screen" do %>
  <%= render 'chat_container' %>
<% end %>